# Generated by Django 5.1 on 2024-08-21 22:55

import django.db.models.deletion
import myclass.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classlist',
            fields=[
                ('title', models.CharField(max_length=75)),
                ('branch', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('academic_year', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('prn', models.CharField(max_length=100, unique=True)),
                ('srno', models.IntegerField(blank=True, default=None, null=True)),
                ('register_number', models.IntegerField(primary_key=True, serialize=False)),
                ('slug2', models.SlugField(blank=True, unique=True)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclass.classlist')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pracs_marks', models.FloatField(blank=True, default=0, null=True)),
                ('theory_marks', models.FloatField(blank=True, default=0, null=True)),
                ('cia_marks', models.FloatField(blank=True, default=0, null=True)),
                ('ciap_marks', models.FloatField(blank=True, default=0, null=True)),
                ('ese', models.FloatField(validators=[myclass.models.validate_ese])),
                ('scaled_ese', models.FloatField(blank=True, null=True)),
                ('esep', models.FloatField(validators=[myclass.models.validate_esep])),
                ('scaled_esep', models.FloatField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='myclass.student')),
            ],
        ),
        migrations.CreateModel(
            name='CIAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciap_cce_final', models.FloatField()),
                ('ciap_cce_component1', models.FloatField(validators=[myclass.models.validate_component1])),
                ('ciap_cce_component2', models.FloatField(validators=[myclass.models.validate_component2])),
                ('ciap_cce_attendance', models.FloatField(validators=[myclass.models.validate_attendance])),
                ('writeup_and_experimentation', models.FloatField(validators=[myclass.models.validate_writeup])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclass.student')),
            ],
        ),
        migrations.CreateModel(
            name='CIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mse', models.FloatField(validators=[myclass.models.validate_mse])),
                ('cia_cce_final', models.FloatField()),
                ('cia_cce_component1', models.FloatField(validators=[myclass.models.validate_cia_component1])),
                ('cia_cce_component2', models.FloatField(validators=[myclass.models.validate_cia_component2])),
                ('cia_cce_attendance', models.FloatField(validators=[myclass.models.validate_cia_attendance])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclass.student')),
            ],
        ),
    ]
