# Generated by Django 5.1 on 2024-08-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slug2',
            field=models.SlugField(blank=True),
        ),
    ]
