# Generated by Django 5.1 on 2024-10-08 05:07

import myclass.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0003_marks_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='ese',
            field=models.FloatField(default=0, validators=[myclass.models.validate_ese]),
        ),
        migrations.AlterField(
            model_name='marks',
            name='esep',
            field=models.FloatField(default=0, validators=[myclass.models.validate_esep]),
        ),
        migrations.AlterField(
            model_name='marks',
            name='scaled_ese',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='scaled_esep',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
